version: '3.1'

services:
  springboot:
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=qlab02
    - MONGO_DB_PASSWORD=qlab02123

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=qlab02
    - MONGO_INITDB_ROOT_PASSWORD=qlab02123
#     volumes:
#       - my-volume:/data/db
#     restart: always
#     networks:
#     - custom-network
#
# volumes:
#   my-volume:
#     external: true
#
# networks:
#   custom-network:
#     external: true
